mode: pool

listener:
  address: 0.0.0.0
  port: 2323
  auth:
    - username: "lmarch2"
      password: "LYFnb@@@"

management:
  enabled: true
  listen: 0.0.0.0:9091
  password: admin123
  probe_target: https://www.google.com

pool:
  mode: sequential
  failure_threshold: 3
  blacklist_duration: 5m

nodes_file: nodes.txt
